TESTS = {
    "Basics": [{
                   "input": (['Norwegian-Dunhill', 'Marlboro-blue', 'Brit-3',
                              'German-coffee', 'beer-white', 'cat-water',
                              'horse-2', 'milk-3', '4-Rothmans',
                              'dog-Swede', 'Norwegian-1', 'horse-Marlboro',
                              'bird-Brit', '4-green', 'Winfield-beer',
                              'Dane-blue', '5-dog', 'blue-horse',
                              'yellow-cat', 'Winfield-Swede', 'tea-Marlboro'], ['horse-cigarettes']),
                   "answer": 'Marlboro',
                   "explanation": "Test 1"},
               {
                   "input": (['Norwegian-Dunhill', 'Marlboro-blue', 'Brit-3',
                              'German-coffee', 'beer-white', 'cat-water',
                              'horse-2', 'milk-3', '4-Rothmans',
                              'dog-Swede', 'Norwegian-1', 'horse-Marlboro',
                              'bird-Brit', '4-green', 'Winfield-beer',
                              'Dane-blue', '5-dog', 'blue-horse',
                              'yellow-cat', 'Winfield-Swede', 'tea-Marlboro'], ['green-num']),
                   "answer": '4',
                   "explanation": "Test 2"
               },
               {
                   "input": (['Norwegian-Dunhill', 'Marlboro-blue', 'Brit-3',
                              'German-coffee', 'beer-white', 'cat-water',
                              'horse-2', 'milk-3', '4-Rothmans',
                              'dog-Swede', 'Norwegian-1', 'horse-Marlboro',
                              'bird-Brit', '4-green', 'Winfield-beer',
                              'Dane-blue', '5-dog', 'blue-horse',
                              'yellow-cat', 'Winfield-Swede', 'tea-Marlboro'], ['milk-colors']),
                   "answer": 'red',
                   "explanation": "Test 3",
               },
               {
                   "input": (['Norwegian-Dunhill', 'Marlboro-blue', 'Brit-3',
                              'German-coffee', 'beer-white', 'cat-water',
                              'horse-2', 'milk-3', '4-Rothmans',
                              'dog-Swede', 'Norwegian-1', 'horse-Marlboro',
                              'bird-Brit', '4-green', 'Winfield-beer',
                              'Dane-blue', '5-dog', 'blue-horse',
                              'yellow-cat', 'Winfield-Swede', 'tea-Marlboro'], ['Winfield-person']),
                   "answer": 'Swede',
                   "explanation": "Test 4",
               },
               {
                   "input": (['Norwegian-Dunhill', 'Marlboro-blue', 'Brit-3',
                              'German-coffee', 'beer-white', 'cat-water',
                              'horse-2', 'milk-3', '4-Rothmans',
                              'dog-Swede', 'Norwegian-1', 'horse-Marlboro',
                              'bird-Brit', '4-green', 'Winfield-beer',
                              'Dane-blue', '5-dog', 'blue-horse',
                              'yellow-cat', 'Winfield-Swede', 'tea-Marlboro'], ['yellow-pets']),
                   "answer": 'cat',
                   "explanation": "Test 5"
               },
    ]}
